-- FraudDetectAI Supabase/Postgres schema
-- Run this entire file in the Supabase SQL editor for the database used by SUPABASE_DB_URL.
-- It is intentionally idempotent and can be re-run after app updates.

set search_path = public;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

-- =========================
-- Users and Access
-- =========================

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null,
    hashed_password text not null,
    role text not null default 'Viewer',
    is_pending_approval boolean not null default false,
    created_at timestamptz not null default timezone('utc', now()),
    constraint users_username_key unique (username),
    constraint users_role_check check (role in ('Admin', 'Analyst', 'Viewer'))
);

create index if not exists idx_users_username on public.users (username);
create index if not exists idx_users_role on public.users (role);
create index if not exists idx_users_pending on public.users (is_pending_approval);
create index if not exists idx_users_created_at on public.users (created_at desc);

-- =========================
-- Audit Logs
-- =========================

create table if not exists public.audit_logs (
    id bigint generated by default as identity primary key,
    username text not null,
    role text not null,
    action text not null,
    details text,
    ip_address text,
    timestamp timestamptz not null default timezone('utc', now())
);

create index if not exists idx_audit_logs_timestamp on public.audit_logs (timestamp desc);
create index if not exists idx_audit_logs_username on public.audit_logs (username);
create index if not exists idx_audit_logs_action on public.audit_logs (action);

-- =========================
-- Notifications
-- =========================
-- target_username is for one-user notifications.
-- target_role is for role/system notifications.
-- read_by/deleted_by store per-user state for shared role/system notifications so one user
-- reading or deleting an alert does not affect another user's notification tray.

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    target_username text,
    target_role text not null default 'All',
    message text not null,
    is_read boolean not null default false,
    read_by jsonb not null default '[]'::jsonb,
    deleted_by jsonb not null default '[]'::jsonb,
    timestamp timestamptz not null default timezone('utc', now()),
    constraint notifications_target_role_check check (target_role in ('All', 'Admin', 'Analyst', 'Viewer'))
);

-- Upgrade older installations that were created before per-user notification state existed.
alter table public.notifications add column if not exists read_by jsonb not null default '[]'::jsonb;
alter table public.notifications add column if not exists deleted_by jsonb not null default '[]'::jsonb;
alter table public.notifications alter column read_by set default '[]'::jsonb;
alter table public.notifications alter column deleted_by set default '[]'::jsonb;
update public.notifications set read_by = '[]'::jsonb where read_by is null;
update public.notifications set deleted_by = '[]'::jsonb where deleted_by is null;

create index if not exists idx_notifications_timestamp on public.notifications (timestamp desc);
create index if not exists idx_notifications_username on public.notifications (target_username);
create index if not exists idx_notifications_role on public.notifications (target_role);
create index if not exists idx_notifications_read_state on public.notifications (is_read);
create index if not exists idx_notifications_read_by on public.notifications using gin (read_by);
create index if not exists idx_notifications_deleted_by on public.notifications using gin (deleted_by);

-- =========================
-- Runtime Risk Settings
-- =========================

create table if not exists public.risk_settings (
    id integer primary key default 1,
    high_threshold double precision not null default 70.0,
    medium_threshold double precision not null default 30.0,
    updated_by text,
    updated_at timestamptz not null default timezone('utc', now()),
    constraint risk_settings_singleton_check check (id = 1),
    constraint risk_settings_threshold_range_check check (
        medium_threshold >= 0.0
        and high_threshold <= 100.0
        and medium_threshold <= high_threshold
    )
);

insert into public.risk_settings (id, high_threshold, medium_threshold)
values (1, 70.0, 30.0)
on conflict (id) do nothing;

drop trigger if exists trg_risk_settings_updated_at on public.risk_settings;
create trigger trg_risk_settings_updated_at
before update on public.risk_settings
for each row
execute function public.set_updated_at();

-- =========================
-- Dataset Metadata
-- =========================
-- Raw CSV rows are not stored here. The current app keeps uploaded data in runtime memory
-- and uses this table only for metadata/recovery features when persistence is enabled.

create table if not exists public.dataset_uploads (
    id bigint generated by default as identity primary key,
    filename text not null,
    uploaded_by text not null,
    total_records integer not null default 0,
    columns_detected jsonb not null default '[]'::jsonb,
    ignored_columns jsonb not null default '[]'::jsonb,
    id_columns jsonb not null default '[]'::jsonb,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    constraint dataset_uploads_total_records_check check (total_records >= 0)
);

comment on table public.dataset_uploads is 'Upload metadata only. Raw CSV rows stay in application memory/runtime state.';

alter table public.dataset_uploads alter column columns_detected type jsonb using columns_detected::jsonb;
alter table public.dataset_uploads alter column ignored_columns type jsonb using ignored_columns::jsonb;
alter table public.dataset_uploads alter column id_columns type jsonb using id_columns::jsonb;

with ranked_uploads as (
    select
        id,
        row_number() over (order by created_at desc, id desc) as active_rank
    from public.dataset_uploads
    where is_active
)
update public.dataset_uploads as upload
set is_active = false
from ranked_uploads
where upload.id = ranked_uploads.id
  and ranked_uploads.active_rank > 1;

create unique index if not exists uq_dataset_uploads_one_active on public.dataset_uploads (is_active) where is_active;
create index if not exists idx_dataset_uploads_active on public.dataset_uploads (is_active, created_at desc, id desc);
create index if not exists idx_dataset_uploads_user on public.dataset_uploads (uploaded_by, created_at desc);

-- =========================
-- Analytics Runs and Results
-- =========================

create table if not exists public.analytics_runs (
    id bigint generated by default as identity primary key,
    upload_id bigint not null references public.dataset_uploads(id) on delete cascade,
    triggered_by text not null,
    high_threshold double precision not null,
    medium_threshold double precision not null,
    total_records integer not null default 0,
    high_risk_count integer not null default 0,
    medium_risk_count integer not null default 0,
    low_risk_count integer not null default 0,
    ae_avg_pct double precision not null default 0.0,
    if_avg_pct double precision not null default 0.0,
    score_scaling jsonb not null default '{}'::jsonb,
    global_feature_impacts jsonb not null default '[]'::jsonb,
    analysis_columns jsonb not null default '[]'::jsonb,
    id_columns jsonb not null default '[]'::jsonb,
    ignored_columns jsonb not null default '[]'::jsonb,
    status text not null default 'completed',
    result_storage_mode text not null default 'all',
    stored_result_rows integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    constraint analytics_runs_status_check check (status in ('completed', 'failed', 'running')),
    constraint analytics_runs_storage_mode_check check (result_storage_mode in ('all', 'limited', 'memory')),
    constraint analytics_runs_counts_check check (
        total_records >= 0
        and high_risk_count >= 0
        and medium_risk_count >= 0
        and low_risk_count >= 0
        and stored_result_rows >= 0
    )
);

alter table public.analytics_runs add column if not exists result_storage_mode text not null default 'all';
alter table public.analytics_runs add column if not exists stored_result_rows integer not null default 0;
alter table public.analytics_runs alter column score_scaling type jsonb using score_scaling::jsonb;
alter table public.analytics_runs alter column global_feature_impacts type jsonb using global_feature_impacts::jsonb;
alter table public.analytics_runs alter column analysis_columns type jsonb using analysis_columns::jsonb;
alter table public.analytics_runs alter column id_columns type jsonb using id_columns::jsonb;
alter table public.analytics_runs alter column ignored_columns type jsonb using ignored_columns::jsonb;

do $$
begin
    if exists (
        select 1
        from information_schema.table_constraints
        where constraint_schema = 'public'
          and table_name = 'analytics_runs'
          and constraint_name = 'analytics_runs_storage_mode_check'
    ) then
        alter table public.analytics_runs drop constraint analytics_runs_storage_mode_check;
    end if;

    alter table public.analytics_runs
    add constraint analytics_runs_storage_mode_check
    check (result_storage_mode in ('all', 'limited', 'memory'));
end;
$$;

with ranked_runs as (
    select
        id,
        row_number() over (order by created_at desc, id desc) as active_rank
    from public.analytics_runs
    where is_active
)
update public.analytics_runs as run
set is_active = false
from ranked_runs
where run.id = ranked_runs.id
  and ranked_runs.active_rank > 1;

create unique index if not exists uq_analytics_runs_one_active on public.analytics_runs (is_active) where is_active;
create index if not exists idx_analytics_runs_active on public.analytics_runs (is_active, created_at desc, id desc);
create index if not exists idx_analytics_runs_upload on public.analytics_runs (upload_id, created_at desc);
create index if not exists idx_analytics_runs_status on public.analytics_runs (status);

create table if not exists public.analytics_results (
    id bigint generated by default as identity primary key,
    run_id bigint not null references public.analytics_runs(id) on delete cascade,
    row_num integer not null,
    record_id text not null,
    category text not null,
    risk_score double precision not null default 0.0,
    ae_error double precision not null default 0.0,
    if_score double precision not null default 0.0,
    created_at timestamptz not null default timezone('utc', now()),
    constraint analytics_results_run_row_key unique (run_id, row_num),
    constraint analytics_results_row_num_check check (row_num > 0),
    constraint analytics_results_category_check check (category in ('high', 'medium', 'low', 'unknown'))
);

comment on table public.analytics_results is 'Persisted scored rows used by dashboards, Customer 360, and recovery after restart.';

create unique index if not exists uq_analytics_results_run_row on public.analytics_results (run_id, row_num);
create index if not exists idx_analytics_results_run_row on public.analytics_results (run_id, row_num);
create index if not exists idx_analytics_results_record_id on public.analytics_results (record_id);
create index if not exists idx_analytics_results_category on public.analytics_results (category);
create index if not exists idx_analytics_results_score on public.analytics_results (risk_score desc);

-- =========================
-- Business Actions
-- =========================

create table if not exists public.business_actions (
    id bigint generated by default as identity primary key,
    record_id text not null,
    action_type text not null,
    executed_by text not null,
    executed_by_role text not null,
    details text,
    status text not null default 'completed',
    created_at timestamptz not null default timezone('utc', now()),
    constraint business_actions_status_check check (status in ('completed', 'failed', 'pending'))
);

create index if not exists idx_business_actions_record_id on public.business_actions (record_id);
create index if not exists idx_business_actions_created_at on public.business_actions (created_at desc);
create index if not exists idx_business_actions_type on public.business_actions (action_type);
create index if not exists idx_business_actions_executed_by on public.business_actions (executed_by, created_at desc);

-- =========================
-- Live Stream Events
-- =========================
-- Current ingestion/live-stream scoring is runtime-first and avoids pushing every streamed row
-- to Supabase. This table remains for compatibility with earlier persistence paths.

create table if not exists public.live_stream_events (
    id bigint generated by default as identity primary key,
    upload_id bigint references public.dataset_uploads(id) on delete set null,
    run_id bigint references public.analytics_runs(id) on delete set null,
    source text not null default 'kafka',
    record_id text not null,
    row_num integer not null,
    category text not null,
    risk_score double precision not null default 0.0,
    ae_error double precision not null default 0.0,
    if_score double precision not null default 0.0,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    constraint live_stream_events_row_num_check check (row_num > 0),
    constraint live_stream_events_category_check check (category in ('high', 'medium', 'low', 'unknown'))
);

comment on table public.live_stream_events is 'Compatibility table for Kafka/manual live-row scoring events and CSV analytics snapshots.';

alter table public.live_stream_events alter column payload type jsonb using payload::jsonb;

create index if not exists idx_live_stream_events_created_at on public.live_stream_events (created_at desc);
create index if not exists idx_live_stream_events_upload on public.live_stream_events (upload_id, created_at desc);
create index if not exists idx_live_stream_events_run on public.live_stream_events (run_id, row_num desc, id desc);
create index if not exists idx_live_stream_events_record_id on public.live_stream_events (record_id);
create index if not exists idx_live_stream_events_category on public.live_stream_events (category);
create index if not exists idx_live_stream_events_source on public.live_stream_events (source);

-- =========================
-- Access-Control Note
-- =========================
-- This app talks to Supabase through the FastAPI backend using SUPABASE_DB_URL/DATABASE_URL.
-- The backend owns role checks and row visibility. Keep direct browser table access disabled
-- unless you add matching Supabase RLS policies.

alter table public.users disable row level security;
alter table public.audit_logs disable row level security;
alter table public.notifications disable row level security;
alter table public.risk_settings disable row level security;
alter table public.dataset_uploads disable row level security;
alter table public.analytics_runs disable row level security;
alter table public.analytics_results disable row level security;
alter table public.business_actions disable row level security;
alter table public.live_stream_events disable row level security;

-- Optional first admin:
--  1. Start the backend and register an Admin through the app, or
--  2. Insert one manually with a bcrypt hash generated by:
--      python -c "from passlib.context import CryptContext; print(CryptContext(schemes=['bcrypt']).hash('change-me'))"
